# Generated by Django 4.2.6 on 2023-11-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlocation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
