# Generated by Django 4.2.6 on 2023-12-17 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_velocity', models.IntegerField(blank=True, null=True)),
                ('maximum_velocity', models.IntegerField(blank=True, null=True)),
                ('minimum_acceleration', models.IntegerField(blank=True, null=True)),
                ('maximum_acceleration', models.IntegerField(blank=True, null=True)),
                ('in_tehran', models.BooleanField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Standards',
                'db_table': 'Standards',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('created_time', models.DateTimeField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.car')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'db_table': 'Locations',
            },
        ),
    ]
