# Generated by Django 4.2.6 on 2023-11-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.IntegerField()),
                ('acceleration', models.IntegerField()),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_speed', models.IntegerField(blank=True, null=True)),
                ('maximum_speed', models.IntegerField(blank=True, null=True)),
                ('minimum_acceleration', models.IntegerField(blank=True, null=True)),
                ('maximum_acceleration', models.IntegerField(blank=True, null=True)),
                ('in_tehran', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Standards',
                'db_table': 'Standards',
            },
        ),
    ]
