# Generated by Django 4.2.6 on 2023-10-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_otp_generateotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerateOtp',
        ),
    ]
